name: fuel_calculator
description: Helpful tools for ACC.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+5

environment:
  sdk: '>=2.17.0 <3.0.0'

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.4
  dropdown_search: 5.0.6
  firebase_analytics: 10.1.6
  firebase_core: 2.8.0
  flutter_svg: 2.0.4
  provider: 6.0.5
  url_launcher: 6.1.10
  shared_preferences: 2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.12.0
  flutter_native_splash: 2.2.19

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/icon/ic_launcher.png"
  adaptive_icon_background: "#05635b"
  adaptive_icon_foreground: "images/icon/splash_icon_padding.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/flags/svg/
    - images/icon/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#009688"
  color_dark: "#303030"
  image: "images/icon/splash_icon.png"
  image_dark: "images/icon/splash_icon.png"