// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLGX3GQ03YvIQrBudKRstmu_iM_ZaGTbs',
    appId: '1:16751703389:web:bfbdfa171420dd825024b4',
    messagingSenderId: '16751703389',
    projectId: 'fuel-calculator-fce7c',
    authDomain: 'fuel-calculator-fce7c.firebaseapp.com',
    storageBucket: 'fuel-calculator-fce7c.appspot.com',
    measurementId: 'G-0WFH1XHWDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXAE30lnSZMWezR_uTyIJ3AgZ2-yH0Au0',
    appId: '1:16751703389:android:97ab10c5ec089f9d5024b4',
    messagingSenderId: '16751703389',
    projectId: 'fuel-calculator-fce7c',
    storageBucket: 'fuel-calculator-fce7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYXSyIA8k4Lx-4YgfR3TEjCS3nfr6iKtc',
    appId: '1:16751703389:ios:ca644ff7149fe17a5024b4',
    messagingSenderId: '16751703389',
    projectId: 'fuel-calculator-fce7c',
    storageBucket: 'fuel-calculator-fce7c.appspot.com',
    iosClientId: '16751703389-2kdu6pvod4gdk20lq24krqojr7ieulva.apps.googleusercontent.com',
    iosBundleId: 'com.mlmorgan.fuel-calculator',
  );
}
